---
- name: Converge
  hosts: all
  become: true
  become_user: root
  tasks:
    # run role
    - block:
        - name: "Include ansible-role-fedmsg"
          include_role:
            name: "ansible-role-fedmsg"
      rescue:
        - debug: msg=haoiu
